FROM python:3.9-slim-buster

WORKDIR /app

COPY 10-Push-to-Kinesis/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY 10-Push-to-Kinesis/lambda_function.py .

CMD ["lambda_function.lambda_handler"]
