FROM python:3.9-slim-buster

WORKDIR /app

COPY 20-Process-stock-data/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY 20-Process-stock-data/lambda_function.py .

CMD ["lambda_function.lambda_handler"]
