FROM python:3.9-slim-buster

WORKDIR /app

COPY 30-export-dynamodb-to-s3/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY 30-export-dynamodb-to-s3/lambda_function.py .

CMD ["lambda_function.lambda_handler"]
